[2025-03-14T12:05:34.477+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-14T12:05:34.493+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: parse_mongo_to_sql_dag.fetch_fallacies manual__2025-03-14T12:05:33.080039+00:00 [queued]>
[2025-03-14T12:05:34.501+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: parse_mongo_to_sql_dag.fetch_fallacies manual__2025-03-14T12:05:33.080039+00:00 [queued]>
[2025-03-14T12:05:34.502+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 5
[2025-03-14T12:05:34.516+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): fetch_fallacies> on 2025-03-14 12:05:33.080039+00:00
[2025-03-14T12:05:34.525+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=4797) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-14T12:05:34.526+0000] {standard_task_runner.py:72} INFO - Started process 4800 to run task
[2025-03-14T12:05:34.531+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'parse_mongo_to_sql_dag', 'fetch_fallacies', 'manual__2025-03-14T12:05:33.080039+00:00', '--job-id', '172', '--raw', '--subdir', 'DAGS_FOLDER/parse2mongo.py', '--cfg-path', '/tmp/tmpr0a7ru33']
[2025-03-14T12:05:34.534+0000] {standard_task_runner.py:105} INFO - Job 172: Subtask fetch_fallacies
[2025-03-14T12:05:34.579+0000] {task_command.py:467} INFO - Running <TaskInstance: parse_mongo_to_sql_dag.fetch_fallacies manual__2025-03-14T12:05:33.080039+00:00 [running]> on host 31c19d57802d
[2025-03-14T12:05:34.669+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='parse_mongo_to_sql_dag' AIRFLOW_CTX_TASK_ID='fetch_fallacies' AIRFLOW_CTX_EXECUTION_DATE='2025-03-14T12:05:33.080039+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-14T12:05:33.080039+00:00'
[2025-03-14T12:05:34.673+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-14T12:05:34.723+0000] {logging_mixin.py:190} INFO - Fetched content for URL: https://en.wikipedia.org/wiki/List_of_fallacies
[2025-03-14T12:05:34.751+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-14T12:05:34.758+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-14T12:05:34.758+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=parse_mongo_to_sql_dag, task_id=fetch_fallacies, run_id=manual__2025-03-14T12:05:33.080039+00:00, execution_date=20250314T120533, start_date=20250314T120534, end_date=20250314T120534
[2025-03-14T12:05:34.821+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-14T12:05:34.827+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
