[2025-03-14T10:46:29.966+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-14T10:46:30.053+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag.third_task scheduled__2025-03-13T00:00:00+00:00 [queued]>
[2025-03-14T10:46:30.112+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag.third_task scheduled__2025-03-13T00:00:00+00:00 [queued]>
[2025-03-14T10:46:30.113+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 5
[2025-03-14T10:46:30.226+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): third_task> on 2025-03-13 00:00:00+00:00
[2025-03-14T10:46:30.239+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=321) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-14T10:46:30.249+0000] {standard_task_runner.py:72} INFO - Started process 346 to run task
[2025-03-14T10:46:30.244+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag', 'third_task', 'scheduled__2025-03-13T00:00:00+00:00', '--job-id', '132', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmpk0gm5q0a']
[2025-03-14T10:46:30.258+0000] {standard_task_runner.py:105} INFO - Job 132: Subtask third_task
[2025-03-14T10:46:30.436+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag.third_task scheduled__2025-03-13T00:00:00+00:00 [running]> on host 857b64da211c
[2025-03-14T10:46:30.733+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='our_first_dag' AIRFLOW_CTX_TASK_ID='third_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-13T00:00:00+00:00'
[2025-03-14T10:46:30.738+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-14T10:46:30.764+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-14T10:46:30.766+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo I am the third task, and I am here to save the day!']
[2025-03-14T10:46:30.779+0000] {subprocess.py:99} INFO - Output:
[2025-03-14T10:46:30.782+0000] {subprocess.py:106} INFO - I am the third task, and I am here to save the day!
[2025-03-14T10:46:30.783+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-14T10:46:30.816+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-14T10:46:30.817+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=our_first_dag, task_id=third_task, run_id=scheduled__2025-03-13T00:00:00+00:00, execution_date=20250313T000000, start_date=20250314T104630, end_date=20250314T104630
[2025-03-14T10:46:30.852+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-14T10:46:30.863+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
