[2025-03-14T10:46:25.900+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-14T10:46:25.954+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag.first_task scheduled__2025-03-10T00:00:00+00:00 [queued]>
[2025-03-14T10:46:26.010+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag.first_task scheduled__2025-03-10T00:00:00+00:00 [queued]>
[2025-03-14T10:46:26.013+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 5
[2025-03-14T10:46:26.142+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): first_task> on 2025-03-10 00:00:00+00:00
[2025-03-14T10:46:26.208+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag', 'first_task', 'scheduled__2025-03-10T00:00:00+00:00', '--job-id', '102', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmpbh7b4oqt']
[2025-03-14T10:46:26.239+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=222) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-14T10:46:26.253+0000] {standard_task_runner.py:105} INFO - Job 102: Subtask first_task
[2025-03-14T10:46:26.263+0000] {standard_task_runner.py:72} INFO - Started process 245 to run task
[2025-03-14T10:46:26.454+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag.first_task scheduled__2025-03-10T00:00:00+00:00 [running]> on host 857b64da211c
[2025-03-14T10:46:26.782+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='our_first_dag' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-10T00:00:00+00:00'
[2025-03-14T10:46:26.814+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-14T10:46:26.920+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-14T10:46:26.939+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo first task! This is something you should see in the logs']
[2025-03-14T10:46:27.011+0000] {subprocess.py:99} INFO - Output:
[2025-03-14T10:46:27.015+0000] {subprocess.py:106} INFO - first task! This is something you should see in the logs
[2025-03-14T10:46:27.019+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-14T10:46:27.118+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-14T10:46:27.120+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=our_first_dag, task_id=first_task, run_id=scheduled__2025-03-10T00:00:00+00:00, execution_date=20250310T000000, start_date=20250314T104625, end_date=20250314T104627
[2025-03-14T10:46:27.589+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-14T10:46:27.712+0000] {taskinstance.py:3901} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2025-03-14T10:46:27.718+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
