[2025-03-19T13:35:06.279+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-19T13:35:06.297+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: parse_mongo_to_sql_dag.store_fallacies manual__2025-03-19T13:35:00.203009+00:00 [queued]>
[2025-03-19T13:35:06.305+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: parse_mongo_to_sql_dag.store_fallacies manual__2025-03-19T13:35:00.203009+00:00 [queued]>
[2025-03-19T13:35:06.306+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 5
[2025-03-19T13:35:06.316+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): store_fallacies> on 2025-03-19 13:35:00.203009+00:00
[2025-03-19T13:35:06.323+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'parse_mongo_to_sql_dag', 'store_fallacies', 'manual__2025-03-19T13:35:00.203009+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/parse2mongo.py', '--cfg-path', '/tmp/tmp79npzg_8']
[2025-03-19T13:35:06.326+0000] {standard_task_runner.py:105} INFO - Job 33: Subtask store_fallacies
[2025-03-19T13:35:06.325+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=572) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-19T13:35:06.326+0000] {standard_task_runner.py:72} INFO - Started process 574 to run task
[2025-03-19T13:35:06.361+0000] {task_command.py:467} INFO - Running <TaskInstance: parse_mongo_to_sql_dag.store_fallacies manual__2025-03-19T13:35:00.203009+00:00 [running]> on host f8578d95b82a
[2025-03-19T13:35:06.422+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='parse_mongo_to_sql_dag' AIRFLOW_CTX_TASK_ID='store_fallacies' AIRFLOW_CTX_EXECUTION_DATE='2025-03-19T13:35:00.203009+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-19T13:35:00.203009+00:00'
[2025-03-19T13:35:06.424+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-19T13:35:06.480+0000] {logging_mixin.py:190} INFO - Data uploaded to PostgreSQL table logical_fallacies.
[2025-03-19T13:35:06.481+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-19T13:35:06.488+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-19T13:35:06.489+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=parse_mongo_to_sql_dag, task_id=store_fallacies, run_id=manual__2025-03-19T13:35:00.203009+00:00, execution_date=20250319T133500, start_date=20250319T133506, end_date=20250319T133506
[2025-03-19T13:35:06.541+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-19T13:35:06.556+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-19T13:35:06.558+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
