[2025-03-13T16:00:14.982+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-13T16:00:14.998+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: parse_mongo_to_sql_dag.parse_task manual__2025-03-13T15:54:09.079378+00:00 [queued]>
[2025-03-13T16:00:15.007+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: parse_mongo_to_sql_dag.parse_task manual__2025-03-13T15:54:09.079378+00:00 [queued]>
[2025-03-13T16:00:15.008+0000] {taskinstance.py:2867} INFO - Starting attempt 4 of 5
[2025-03-13T16:00:15.019+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): parse_task> on 2025-03-13 15:54:09.079378+00:00
[2025-03-13T16:00:15.025+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=5860) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-13T16:00:15.026+0000] {standard_task_runner.py:72} INFO - Started process 5862 to run task
[2025-03-13T16:00:15.026+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'parse_mongo_to_sql_dag', 'parse_task', 'manual__2025-03-13T15:54:09.079378+00:00', '--job-id', '90', '--raw', '--subdir', 'DAGS_FOLDER/parse2mongo.py', '--cfg-path', '/tmp/tmp98dm3_0r']
[2025-03-13T16:00:15.028+0000] {standard_task_runner.py:105} INFO - Job 90: Subtask parse_task
[2025-03-13T16:00:15.064+0000] {task_command.py:467} INFO - Running <TaskInstance: parse_mongo_to_sql_dag.parse_task manual__2025-03-13T15:54:09.079378+00:00 [running]> on host 40f8d416e5ba
[2025-03-13T16:00:15.120+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='parse_mongo_to_sql_dag' AIRFLOW_CTX_TASK_ID='parse_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-13T15:54:09.079378+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-13T15:54:09.079378+00:00'
[2025-03-13T16:00:15.121+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-13T16:00:15.138+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/parse2mongo.py", line 27, in parse_task
    raise ValueError("No content fetched from MongoDB.")
ValueError: No content fetched from MongoDB.
[2025-03-13T16:00:15.152+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=parse_mongo_to_sql_dag, task_id=parse_task, run_id=manual__2025-03-13T15:54:09.079378+00:00, execution_date=20250313T155409, start_date=20250313T160014, end_date=20250313T160015
[2025-03-13T16:00:15.175+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-13T16:00:15.176+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 90 for task parse_task (No content fetched from MongoDB.; 5862)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/parse2mongo.py", line 27, in parse_task
    raise ValueError("No content fetched from MongoDB.")
ValueError: No content fetched from MongoDB.
[2025-03-13T16:00:15.201+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-13T16:00:15.218+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-13T16:00:15.221+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
