[2025-03-14T10:46:29.844+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-14T10:46:29.928+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag.second_task scheduled__2025-03-13T00:00:00+00:00 [queued]>
[2025-03-14T10:46:29.974+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag.second_task scheduled__2025-03-13T00:00:00+00:00 [queued]>
[2025-03-14T10:46:29.976+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 5
[2025-03-14T10:46:30.056+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): second_task> on 2025-03-13 00:00:00+00:00
[2025-03-14T10:46:30.070+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=318) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-14T10:46:30.072+0000] {standard_task_runner.py:72} INFO - Started process 343 to run task
[2025-03-14T10:46:30.106+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag', 'second_task', 'scheduled__2025-03-13T00:00:00+00:00', '--job-id', '131', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmpch79hz8r']
[2025-03-14T10:46:30.112+0000] {standard_task_runner.py:105} INFO - Job 131: Subtask second_task
[2025-03-14T10:46:30.332+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag.second_task scheduled__2025-03-13T00:00:00+00:00 [running]> on host 857b64da211c
[2025-03-14T10:46:30.624+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='our_first_dag' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-13T00:00:00+00:00'
[2025-03-14T10:46:30.628+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-14T10:46:30.675+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-14T10:46:30.680+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo I am task two, but it failed somehow?']
[2025-03-14T10:46:30.702+0000] {subprocess.py:99} INFO - Output:
[2025-03-14T10:46:30.704+0000] {subprocess.py:106} INFO - I am task two, but it failed somehow?
[2025-03-14T10:46:30.705+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-14T10:46:30.744+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-14T10:46:30.746+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=our_first_dag, task_id=second_task, run_id=scheduled__2025-03-13T00:00:00+00:00, execution_date=20250313T000000, start_date=20250314T104629, end_date=20250314T104630
[2025-03-14T10:46:30.798+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-14T10:46:30.812+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
