[2025-03-19T13:35:03.497+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-19T13:35:03.515+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: parse_mongo_to_sql_dag.parse_fallacies manual__2025-03-19T13:35:00.203009+00:00 [queued]>
[2025-03-19T13:35:03.522+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: parse_mongo_to_sql_dag.parse_fallacies manual__2025-03-19T13:35:00.203009+00:00 [queued]>
[2025-03-19T13:35:03.523+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 5
[2025-03-19T13:35:03.534+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): parse_fallacies> on 2025-03-19 13:35:00.203009+00:00
[2025-03-19T13:35:03.542+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=565) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-19T13:35:03.544+0000] {standard_task_runner.py:72} INFO - Started process 569 to run task
[2025-03-19T13:35:03.546+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'parse_mongo_to_sql_dag', 'parse_fallacies', 'manual__2025-03-19T13:35:00.203009+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/parse2mongo.py', '--cfg-path', '/tmp/tmpt5f69nfv']
[2025-03-19T13:35:03.548+0000] {standard_task_runner.py:105} INFO - Job 32: Subtask parse_fallacies
[2025-03-19T13:35:03.588+0000] {task_command.py:467} INFO - Running <TaskInstance: parse_mongo_to_sql_dag.parse_fallacies manual__2025-03-19T13:35:00.203009+00:00 [running]> on host f8578d95b82a
[2025-03-19T13:35:03.657+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='parse_mongo_to_sql_dag' AIRFLOW_CTX_TASK_ID='parse_fallacies' AIRFLOW_CTX_EXECUTION_DATE='2025-03-19T13:35:00.203009+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-19T13:35:00.203009+00:00'
[2025-03-19T13:35:03.658+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-19T13:35:05.583+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-19T13:35:05.590+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-19T13:35:05.591+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=parse_mongo_to_sql_dag, task_id=parse_fallacies, run_id=manual__2025-03-19T13:35:00.203009+00:00, execution_date=20250319T133500, start_date=20250319T133503, end_date=20250319T133505
[2025-03-19T13:35:05.643+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-19T13:35:05.663+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-19T13:35:05.665+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
