[2025-03-14T10:46:29.543+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-14T10:46:29.591+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag.third_task scheduled__2025-03-09T00:00:00+00:00 [queued]>
[2025-03-14T10:46:29.617+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag.third_task scheduled__2025-03-09T00:00:00+00:00 [queued]>
[2025-03-14T10:46:29.618+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 5
[2025-03-14T10:46:29.702+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): third_task> on 2025-03-09 00:00:00+00:00
[2025-03-14T10:46:29.719+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag', 'third_task', 'scheduled__2025-03-09T00:00:00+00:00', '--job-id', '128', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmpreib8e18']
[2025-03-14T10:46:29.724+0000] {standard_task_runner.py:105} INFO - Job 128: Subtask third_task
[2025-03-14T10:46:29.779+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=306) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-14T10:46:29.816+0000] {standard_task_runner.py:72} INFO - Started process 332 to run task
[2025-03-14T10:46:29.899+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag.third_task scheduled__2025-03-09T00:00:00+00:00 [running]> on host 857b64da211c
[2025-03-14T10:46:30.294+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='our_first_dag' AIRFLOW_CTX_TASK_ID='third_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-09T00:00:00+00:00'
[2025-03-14T10:46:30.295+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-14T10:46:30.347+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-14T10:46:30.349+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo I am the third task, and I am here to save the day!']
[2025-03-14T10:46:30.374+0000] {subprocess.py:99} INFO - Output:
[2025-03-14T10:46:30.378+0000] {subprocess.py:106} INFO - I am the third task, and I am here to save the day!
[2025-03-14T10:46:30.379+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-14T10:46:30.444+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-14T10:46:30.446+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=our_first_dag, task_id=third_task, run_id=scheduled__2025-03-09T00:00:00+00:00, execution_date=20250309T000000, start_date=20250314T104629, end_date=20250314T104630
[2025-03-14T10:46:30.583+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-14T10:46:30.628+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-14T10:46:30.641+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
