[2025-03-14T10:46:29.256+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-14T10:46:29.365+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag.second_task scheduled__2025-03-09T00:00:00+00:00 [queued]>
[2025-03-14T10:46:29.442+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag.second_task scheduled__2025-03-09T00:00:00+00:00 [queued]>
[2025-03-14T10:46:29.462+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 5
[2025-03-14T10:46:29.657+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): second_task> on 2025-03-09 00:00:00+00:00
[2025-03-14T10:46:29.689+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag', 'second_task', 'scheduled__2025-03-09T00:00:00+00:00', '--job-id', '121', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmprzdebo5a']
[2025-03-14T10:46:29.710+0000] {standard_task_runner.py:105} INFO - Job 121: Subtask second_task
[2025-03-14T10:46:29.732+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=307) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-14T10:46:29.742+0000] {standard_task_runner.py:72} INFO - Started process 326 to run task
[2025-03-14T10:46:29.874+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag.second_task scheduled__2025-03-09T00:00:00+00:00 [running]> on host 857b64da211c
[2025-03-14T10:46:30.253+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='our_first_dag' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-09T00:00:00+00:00'
[2025-03-14T10:46:30.275+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-14T10:46:30.377+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-14T10:46:30.386+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo I am task two, but it failed somehow?']
[2025-03-14T10:46:30.419+0000] {subprocess.py:99} INFO - Output:
[2025-03-14T10:46:30.421+0000] {subprocess.py:106} INFO - I am task two, but it failed somehow?
[2025-03-14T10:46:30.422+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-14T10:46:30.499+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-14T10:46:30.500+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=our_first_dag, task_id=second_task, run_id=scheduled__2025-03-09T00:00:00+00:00, execution_date=20250309T000000, start_date=20250314T104629, end_date=20250314T104630
[2025-03-14T10:46:30.605+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-14T10:46:30.621+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
